/**
 * The agent's event trail (store.recordEvent, the `trace` in routes) in plain
 * words: what a step means to the person watching a card say REBUILDING.
 * Unknown events fall back to their name, so nothing is ever hidden.
 */
const LABELS: Record<string, string | ((d: Record<string, unknown>) => string)> = {
  'runtime.seeding': (d) => d.migrating
    ? 'writing its settings and running OpenClaw\'s upgrade migrations (minutes on an agent with a long history)'
    : 'writing its settings into the volume',
  'runtime.provisioned': 'container created',
  'runtime.started': 'container started, waiting for the gateway',
  'runtime.healthy': 'gateway answered',
  'runtime.syncing': 'syncing data folders, connections and skills',
  'datasource.git_synced': (d) => `data folder synced: ${String(d.mountName ?? '')}`.trim(),
  'installdocs.synced': 'install notes synced',
  'agentsmd.synced': 'AGENTS.md synced',
  'connection.sync_failed': (d) => `a connection did not sync: ${String(d.error ?? '')}`.trim(),
  'runtime.settling': 'waiting for its skills to settle',
  'runtime.ready': (d) => d.settled === false ? 'skills did not settle in time — carrying on' : 'skills settled',
  'memory.reindex': (d) => d.why === 'index incomplete'
    ? 'rebuilding the memory index — it came up partial (minutes on a big memory)'
    : `re-indexing memory on ${d.engine === 'shared' ? 'the shared engine' : 'its own engine'} (minutes on a big memory)`,
  'memory.reindex_retry': 'memory index failed once — trying again in 15 s',
  'memory.reindexed': 'memory index ready',
  'memory.reindex_failed': (d) => `memory index failed: ${String(d.error ?? '')}`.trim(),
  'memory.reindex_not_ready': 'memory search not answering after the index',
  'runtime.rebuilt': 'rebuild finished — running',
  'runtime.self_restarted': (d) => {
    const code = typeof d.exitCode === 'number' ? d.exitCode : undefined;
    const why = code === 137 ? 'killed for memory (exit 137)' : code === 0 ? 'quit cleanly (exit 0) without saying why' : code !== undefined ? `exit ${code}` : 'exit unknown';
    return `its OpenClaw process quit on its own — ${why} — and Docker started it again (time ${d.count ?? '?'} since the last rebuild)`;
  },
  'rebuild.failed': (d) => `rebuild failed: ${String(d.reason ?? d.error ?? '')}`.trim(),
  'rebuild.abandoned': 'rebuild abandoned (the agent is being deleted)',
  'rebuild.auto': 'rebuilt by the machine on its own',
  'provision.failed': (d) => `setup failed: ${String(d.reason ?? d.error ?? '')}`.trim(),
  'embed.baked_instead': (d) => `built on its own memory engine — ${String(d.why ?? '')}`,
  'embed.forced_shared': 'its image has no memory engine: using the shared service',
  'embed.engineless_refused': 'its image has no memory engine and the shared service is unavailable',
  'embed.mode': 'memory search engine switched',
  'memory.peaks_cleared': 'memory peak and cap-hit readings cleared',
  'memory.cap_set': (d) => `memory cap ${d.cap === 'default' ? 'back to the default' : d.cap === 'class' ? 'set by its class' : 'set'}: ${String(d.effective ?? '')}${d.live ? ' — applied to the running container' : ''}`,
  'snapshot.captured': 'memory files snapshotted',
  'memory.checkpointed': 'conversation written to memory',
  'channel.dm_policy': 'chat access policy applied',
  'channel.rechecked': (d) => `${String(d.kind ?? 'channel')} checked again with the platform${Number(d.warnings) ? ` — ${d.warnings} thing${d.warnings === 1 ? '' : 's'} to fix` : ' — all good'}`,
  'channel.attached': (d) => `${String(d.kind ?? 'a channel')} connected`,
  'channel.renamed': (d) => d.ok
    ? `${String(d.kind ?? 'telegram')} bot renamed to “${String(d.name ?? '')}”`
    : `${String(d.kind ?? 'telegram')} bot rename refused${d.note || d.error ? ` — ${String(d.note ?? d.error)}` : ''}`,
  'channel.detached': (d) => `${String(d.kind ?? 'a channel')} removed${Number(d.told) ? ` — ${d.told} told` : ''}`,
  'channel.swapped': (d) => `${String(d.kind ?? 'telegram')} bot changed: ${String(d.from ?? '?')} → ${String(d.to ?? '?')}${Number(d.told) ? ` — ${d.told} told where to find it` : ''}`,
  'channel.park_failed': (d) => `${String(d.kind ?? 'discord')} bot could not be parked; its token was discarded`,
  'channel.recycle_failed': 'the bot could not be parked in the pool; its token was discarded',
  'channel.allowlist_scrubbed': (d) => `${String(d.kind ?? 'channel')}: everyone it had admitted was forgotten${Number(d.removed) ? ` (${d.removed})` : ''}`,
  'channel.allowlist_scrub_failed': (d) => `${String(d.kind ?? 'channel')}: its old approvals could not be cleared — the rebuild writes the list afresh`,
  'channel.farewell': (d) => `${String(d.kind ?? 'channel')}: ${Number(d.told) || 0} people told it no longer answers there`,
  'channel.reassigned_marked': (d) => `${String(d.kind ?? 'discord')}: ${Number(d.told) || 0} people told this bot now serves this agent`,
  'members.announced': (d) => `${Number(d.sent) || 0} of ${Number(d.of) || 0} people told on ${String(d.kind ?? 'telegram')}`,
  'agent.allow_knocks': (d) => (d.on ? 'anyone may knock now' : 'invite only now'),
  'agent.hibernated': (d) => `asleep — ${String(d.why ?? 'idle')}; it wakes on a message`,
  'agent.woken': (d) => `woke up: ${String(d.why ?? '')}`.trim(),
  'hibernate.failed': (d) => `could not put it to sleep: ${String(d.error ?? '')}`.trim(),
  'hibernate.wake_failed': (d) => `could not wake it: ${String(d.error ?? '')}`.trim(),
  'channel.rooms': (d) => `${String(d.kind ?? 'channel')} group chats: ${d.mode === 'room' ? 'one room' : 'off'}`,
  'channel.skipped': 'a messaging channel was skipped (not on this image)',
  'channel.setup_required': 'waiting for a bot token',
  'telegram.skipped': 'continuing without Telegram',
  'console.device_approved': 'console device approved',
  'owner.ask': 'a message from its owner',
  'agent.exported': 'exported',
  'agent.archived': 'archived',
  'ops.created': 'the manager was created',
  // ---- the rest of the trail (review 2026-09-25: every emitted event has words) ----
  'a2a.consult': (d) => `asked ${String(d.peer ?? d.target ?? 'another agent')}`,
  'a2a.consulted': (d) => `answered ${String(d.from ?? d.peer ?? 'another agent')}`,
  'adopt.import_failed': (d) => `adopting the workspace failed: ${String(d.error ?? '')}`.trim(),
  'adopt.path_rewrite_error': 'a task path could not be rewritten for the container',
  'adopt.path_rewrite_failed': 'a task path could not be rewritten for the container',
  'adopt.path_rewrite_skipped': 'task paths left as they were',
  'adopt.repoint_busy': 'workspace re-point skipped — the agent is busy',
  'agent.adopted_workspace': 'workspace adopted',
  'agent.derived': (d) => `derived from ${String(d.masterName ?? d.master ?? 'its master')}`,
  'agent.imported': 'imported',
  'agent.moved': (d) => `moved to ${String(d.toHost ?? d.host ?? 'another host')}`,
  'agent.restored': 'restored from a backup',
  'agentsmd.sync_error': 'AGENTS.md did not sync',
  'agentsmd.sync_failed': 'AGENTS.md did not sync',
  'app.public_url_written': (d) => `links now use ${String(d.url ?? 'the new address')}`,
  'archive.recycle_failed': 'its bot could not go back to the pool; the token was discarded',
  'auth.family_accounts_on': 'family accounts turned on',
  'channel.provisioned': (d) => `${String(d.kind ?? 'its bot')} set up`,
  'claim.approve_failed': (d) => `letting someone in failed: ${String(d.error ?? '')}`.trim(),
  'claim.bound': 'its owner linked from the first message',
  'claim.window_abandoned': 'the first-contact window was given up',
  'claim.window_closed': 'the first-contact window closed',
  'connection.attached': (d) => `connection ${String(d.name ?? d.kind ?? '')} attached`.trim(),
  'connection.detached': (d) => `connection ${String(d.name ?? d.kind ?? '')} detached`.trim(),
  'connection.linked': (d) => `${String(d.kind ?? 'a')} account connected`,
  'connection.removed': (d) => `${String(d.kind ?? 'a')} account removed`,
  'connection.unlinked': (d) => `${String(d.kind ?? 'a')} account disconnected`,
  'context.reset_after_rebuild': 'started a fresh conversation after the rebuild',
  'cron.created': (d) => `task “${String(d.name ?? '')}” created`,
  'cron.migrate_error': 'a task could not be brought over',
  'cron.migrate_failed': 'a task could not be brought over',
  'cron.migrate_gateway_not_ready': 'tasks not brought over yet — the gateway was not ready',
  'cron.migrate_skipped': 'tasks left where they were',
  'cron.migrate_unmappable': 'a task could not be mapped to this agent',
  'cron.triggers': (d) => `task “${String(d.name ?? d.jobId ?? '')}” run by hand`,
  'datasource.git_sync_error': (d) => `data folder did not sync: ${String(d.mountName ?? d.error ?? '')}`.trim(),
  'datasource.git_sync_failed': (d) => `data folder did not sync: ${String(d.mountName ?? d.error ?? '')}`.trim(),
  'definition.pushed': (d) => `definition pushed to ${Number(d.count ?? d.to ?? 0) || 'its'} children`,
  'derived.remove_failed': 'Docker would not remove the image',
  'embed.default_set': 'default memory search engine set',
  'embed.auto_started': (d) => String(d.by ?? '').startsWith('boot')
    ? 'the memory search service was turned on at start-up (the runtime image has no engine of its own)'
    : 'the memory search service was turned on for this agent',
  'embed.move_all': 'every agent moved to the shared memory search',
  'export.restart_failed': 'did not restart after the export',
  'host.drain_stop_failed': 'an agent would not stop for the drain',
  'image.ensure': 'runtime image checked',
  'image.rebuilt_from_recipe': 'image rebuilt from its recipe',
  'image.unpinned': 'back on the default image',
  'import.rollback_step_failed': 'a step of the import rollback failed',
  'import.rolled_back': 'import rolled back',
  'installdocs.error': 'install notes did not sync',
  'installdocs.failed': 'install notes did not sync',
  'member.added_known': (d) => `${String(d.displayName ?? d.name ?? 'someone known')} added`,
  'member.admitted': (d) => `${String(d.displayName ?? d.name ?? 'someone')} let in`,
  'member.allowlist_granted': 'someone was allowed on the door',
  'member.allowlist_scrubbed': 'old approvals cleared from the door',
  'member.door_reopened': 'the door reopened for a returning member',
  'member.known_admitted': (d) => `${String(d.displayName ?? d.name ?? 'someone known')} let straight in`,
  'member.owner_self_claim': 'its owner claimed it',
  'member.revoked': (d) => `${String(d.displayName ?? d.name ?? 'someone')} removed`,
  'member.telegram_linked': 'a member linked their Telegram',
  'member.welcome_failed': 'the welcome message did not send',
  'memory.checkpoint_failed': 'the conversation could not be written to memory',
  'memory.checkpoint_notified': 'told about the memory checkpoint',
  'migrate.done': 'moved to the other server',
  'migrate.exported': 'exported for the move',
  'migrate.landed_despite_error': 'landed on the other server despite an error here',
  'migrate.pool_retire_failed': 'its bot could not be retired from the pool here',
  'migrate.preflight_ok': 'the other server is ready for it',
  'migrate.restart_failed': 'did not restart after the failed move',
  'migrate.rolled_back': 'move rolled back',
  'model.live_set_failed': 'the running agent did not take the new model — it applies at the next rebuild',
  'move.rollback_orphan': 'a copy may be left on the target host',
  'move.rolled_back': 'move rolled back',
  'move.source_cleanup_failed': 'the old copy could not be removed',
  'move.source_restart_failed': 'did not restart on the old host after the failed move',
  'ops.door_unavailable': 'the manager\'s door was not reachable',
  'ops.mcp_error': 'a manager tool call failed',
  'ops.peer_refused': 'a peer was refused at the door',
  'ops.proxy_busy': 'the door was busy',
  'ops.proxy_refused': 'a request was refused at the door',
  'ops.suggest_asked': 'the manager was asked for suggestions',
  'pairing.denied': 'a request to talk was turned down',
  'pairing.stranger_turned_away': 'a stranger knocked and was turned away',
  'params.applied': 'setup values applied',
  'peer_tools.failed': 'its peer tool did not install',
  'proposal.created': (d) => `proposal “${String(d.title ?? d.name ?? '')}” created`.replace(' “”', ''),
  'proposal.merged': 'proposal merged',
  'rebuild.concurrency_set': (d) => `rebuild at once set to ${String(d.value ?? d.concurrency ?? '')}`.trim(),
  'rebuild.on_start': 'rebuilt at start-up',
  'rebuild.policy_set': (d) => `automatic rebuilds: ${String(d.policy ?? d.mode ?? 'changed')}`,
  'rebuild_hook.error': 'its rebuild hook failed',
  'rebuild_hook.failed': 'its rebuild hook failed',
  'rebuild_hook.ran': 'its rebuild hook ran',
  'reconcile.error': 'the state check hit an error',
  'reconcile.host_unreachable': 'its host could not be reached',
  'reconcile.interrupted': 'the state check was interrupted',
  'reconcile.loop_error': 'the state check loop hit an error',
  'reconcile.marked_running': 'found running',
  'reconcile.marked_stopped': 'found stopped',
  'reconcile.runtime_error': 'its container could not be checked',
  'reconcile.runtime_missing': 'its container is gone',
  'reconcile.unhealthy': 'its gateway is not answering',
  'restore.restart_failed': 'did not restart after the restore',
  'restore.rollback_failed': 'the restore could not be rolled back',
  'restore.safety_capture_failed': 'the pre-restore safety snapshot failed',
  'rollback.failed': 'rolling back the failed rebuild did not work',
  'schedule.already_present': 'its tasks were already in place',
  'schedule.applied': 'tasks written',
  'schedule.apply_failed': 'tasks could not be written',
  'snapshot.restored': 'memory files restored from a snapshot',
  'snapshot.safety_failed': 'the pre-restore safety snapshot failed',
  'source.migrated': (d) => `AI source moved to ${String(d.to ?? d.name ?? 'another source')}`,
  'tailscale.serve_enabled': 'HTTPS on the tailnet turned on',
  'transcript.exported': 'conversation exported',
  'transcript.recover_after_switch': 'earlier conversation restored after the source switch',
  'transcript.recover_started': 'restoring an earlier conversation',
};

export function eventLabel(event: string, detail?: Record<string, unknown>): string {
  const l = LABELS[event];
  if (!l) return event;
  return typeof l === 'function' ? l(detail ?? {}) : l;
}

/** Steps that mean "still working" when they are the newest event of a busy agent. */
export const IN_PROGRESS = new Set(['runtime.seeding', 'runtime.provisioned', 'runtime.started', 'runtime.healthy', 'runtime.syncing', 'runtime.settling', 'memory.reindex', 'memory.reindex_retry', 'datasource.git_synced', 'installdocs.synced', 'agentsmd.synced', 'runtime.ready']);
